version: "3.8"

services:

  frontend:
    image: nginx:latest
    volumes:
      - ./frontend/dist:/usr/share/nginx/html  # El build de React
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - captive_network

  backend:
    build:
      context: ./backend
    environment:
      - NODE_ENV=production
    networks:
      - captive_network

networks:
  captive_network:
