version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:3000"  # Redirige el tráfico de la máquina (80) al contenedor (3000)
    environment:
      - NODE_ENV=production
    restart: always
